# k8s-manifest.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-backend
spec:
  replicas: 1 # file download could be fail if we have multiple replicas. Need to fix it later (add file storage server)
  selector:
    matchLabels:
      app: blog-backend
  template:
    metadata:
      labels:
        app: blog-backend
    spec:
      containers:
        - name: blog-backend
          image: bloomingflower/blog-backend:latest
          imagePullPolicy: Always
          env:
            - name: BASE_URL
              value: "https://blog.yourrubber.duckdns.org"
          ports:
            - containerPort: 8008
---
apiVersion: v1
kind: Service
metadata:
  name: blog-backend
spec:
  selector:
    app: blog-backend
  ports:
    - name: https-blog
      port: 443
      targetPort: 8008
  type: ClusterIP
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: blog-backend-virtualservice
spec:
  hosts:
    - "blog.yourrubber.duckdns.org"
  gateways:
    - blog-gateway
  http:
    - match:
        - uri:
            prefix: "/api/v1/"
      route:
        - destination:
            host: blog-backend.default.svc.cluster.local
            port:
              number: 443
