---
apiVersion: v1
kind: ConfigMap
metadata:
  name: blog-redis-cluster
  labels:
    app: blog-redis-cluster
data:
  update-node.sh: |
    #!/bin/sh
    REDIS_NODES="/data/nodes.conf"
    sed -i -e "/myself/ s/[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}/${POD_IP}/" ${REDIS_NODES}
    exec "$@"
  redis.conf: |+
    cluster-enabled yes
    cluster-config-file /data/nodes.conf
    cluster-node-timeout 5000
    appendonly yes
    protected-mode no
    maxmemory 512mb
    maxmemory-policy allkeys-lru

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: blog-redis-cluster
spec:
  serviceName: "blog-redis-cluster"
  replicas: 2
  selector:
    matchLabels:
      app: blog-redis-cluster
  template:
    metadata:
      labels:
        app: blog-redis-cluster
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - blog-redis-cluster
              topologyKey: kubernetes.io/hostname
      initContainers:
      - name: init-redis-cluster
        image: redis:latest
        command:
        - sh
        - -c
        - |
          echo "Waiting for redis nodes to be ready..."
          until redis-cli -h blog-redis-cluster-0.blog-redis-cluster -p 6379 ping; do sleep 1; done
          until redis-cli -h blog-redis-cluster-1.blog-redis-cluster -p 6379 ping; do sleep 1; done
          echo "Creating Redis cluster..."
          redis-cli --cluster create \
            blog-redis-cluster-0.blog-redis-cluster:6379 \
            blog-redis-cluster-1.blog-redis-cluster:6379 \
            --cluster-replicas 0 \
            --cluster-yes
      containers:
      - name: redis
        image: redis:latest
        # resources:
        #   requests:
        #     cpu: 100m
        #     memory: 128Mi
        #   limits:
        #     cpu: 200m
        #     memory: 256Mi
        ports:
        - containerPort: 6379
          name: client
        - containerPort: 16379
          name: gossip
        command: ["redis-server", "/conf/redis.conf"]
        args: ["--protected-mode", "no"]
        readinessProbe:
          exec:
            command:
              - sh
              - -c
              - "redis-cli -h localhost -a $REDIS_PASSWORD ping"
          initialDelaySeconds: 15
          timeoutSeconds: 5
        livenessProbe:
          exec:
            command:
              - sh
              - -c
              - "redis-cli -h localhost -a $REDIS_PASSWORD ping"
          initialDelaySeconds: 20
          periodSeconds: 3
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        envFrom:
        - secretRef:
            name: redis-secret
        volumeMounts:
        - name: conf
          mountPath: /conf
          readOnly: false
      volumes:
      - name: conf
        configMap:
          name: blog-redis-cluster
          defaultMode: 0755

---
apiVersion: v1
kind: Service
metadata:
  name: blog-redis-cluster
spec:
  selector:
    app: blog-redis-cluster
  ports:
  - port: 6379
    targetPort: 6379
  clusterIP: None