---
apiVersion: v1
kind: ConfigMap
metadata:
  name: blog-redis
  labels:
    app: blog-redis
data:
  redis.conf: |+
    appendonly yes
    protected-mode no
    maxmemory 512mb
    maxmemory-policy allkeys-lru

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-redis
  template:
    metadata:
      labels:
        app: blog-redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379
          name: redis
        command: ["redis-server", "/conf/redis.conf"]
        readinessProbe:
          exec:
            command:
              - sh
              - -c
              - "redis-cli -h localhost -a $REDIS_PASSWORD ping"
          initialDelaySeconds: 15
          timeoutSeconds: 5
        livenessProbe:
          exec:
            command:
              - sh
              - -c
              - "redis-cli -h localhost -a $REDIS_PASSWORD ping"
          initialDelaySeconds: 20
          periodSeconds: 3
        envFrom:
        - secretRef:
            name: redis-secret
        volumeMounts:
        - name: conf
          mountPath: /conf
          readOnly: true
      volumes:
      - name: conf
        configMap:
          name: blog-redis
          defaultMode: 0644

---
apiVersion: v1
kind: Service
metadata:
  name: blog-redis
spec:
  selector:
    app: blog-redis
  ports:
  - port: 6379
    targetPort: 6379