# k8s-manifest.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-axum
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-axum
  template:
    metadata:
      labels:
        app: blog-axum
    spec:
      containers:
        - name: axum-backend
          image: bloomingflower/axum-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
          envFrom:
            - secretRef:
                name: blog-axum-secret
---
apiVersion: v1
kind: Service
metadata:
  name: blog-axum
spec:
  selector:
    app: blog-axum
  ports:
    - name: https-blog
      port: 443
      targetPort: 8001
  type: ClusterIP
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: blog-axum-virtualservice
spec:
  hosts:
    - "blog.yourrubber.duckdns.org"
  gateways:
    - blog-gateway
  http:
    - match:
        - uri:
            prefix: "/api/v2/"
      route:
        - destination:
            host: blog-axum.default.svc.cluster.local
            port:
              number: 443
