# k8s-manifest.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-scratch
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blog-scratch
  template:
    metadata:
      labels:
        app: blog-scratch
    spec:
      containers:
        - name: blog-scratch
          image: bloomingflower/blog-scratch:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: blog-scratch
spec:
  selector:
    app: blog-scratch
  ports:
    - name: grpc
      protocol: TCP
      port: 50031
      targetPort: 50051
  type: ClusterIP
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: blog-scratch-virtualservice
  namespace: default
spec:
  hosts:
  - "blog.yourrubber.duckdns.org"
  gateways:
  - blog-gateway
  http:
  - match:
    - uri:
        prefix: "/grpc.reflection.v1.ServerReflection"
    route:
    - destination:
        host: blog-scratch.default.svc.cluster.local
        port:
          number: 50031
  - match:
    - uri:
        prefix: "/api.ApiService"
    route:
    - destination:
        host: blog-scratch.default.svc.cluster.local
        port:
          number: 50031
