# k8s-manifest.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-scratch
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blog-scratch
  template:
    metadata:
      labels:
        app: blog-scratch
    spec:
      containers:
        - name: blog-scratch
          image: bloomingflower/blog-scratch:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: blog-scratch
spec:
  selector:
    app: blog-scratch
  ports:
    - name: grpc
      protocol: TCP
      port: 50031
      targetPort: 50051
  type: ClusterIP
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: blog-scratch-virtualservice
spec:
  gateways:
    - blog-gateway
  hosts:
    - blog.yourrubber.duckdns.org
  http:
    - match:
        - uri:
            prefix: /grpc.reflection.v1.ServerReflection
      route:
        - destination:
            host: blog-scratch.default.svc.cluster.local
            port:
              number: 50031
      corsPolicy:
        allowOrigins:
        - exact: https://blog.yourrubber.duckdns.org
        - exact: https://blog.yourrubber.duckdns.org:50031
        allowMethods:
        - POST
        - GET
        - OPTIONS
        - PUT
        - DELETE
        allowHeaders:
        - Content-Type
        - Authorization
        - x-grpc-web
        - grpc-timeout
        - keep-alive
        - cache-control
        - x-user-agent
        - set
        - get
        - has
        - delete
        - append
        - foreach
        - headersmap
        - toheaders
        - appendfromstring
        - api_key
        maxAge: 1728s
        exposeHeaders:
        - custom-header-1
        - grpc-status
        - grpc-message
        allowCredentials: true
    - match:
        - uri:
            prefix: /api.ApiService
      route:
        - destination:
            host: blog-scratch.default.svc.cluster.local
            port:
              number: 50031
      corsPolicy:
        allowOrigins:
        - exact: https://blog.yourrubber.duckdns.org
        - exact: https://blog.yourrubber.duckdns.org:50031
        allowMethods:
        - POST
        - GET
        - OPTIONS
        - PUT
        - DELETE
        allowHeaders:
        - Content-Type
        - Authorization
        - x-grpc-web
        - grpc-timeout
        - keep-alive
        - cache-control
        - x-user-agent
        - set
        - get
        - has
        - delete
        - append
        - foreach
        - headersmap
        - toheaders
        - appendfromstring
        - api_key
        maxAge: 1728s
        exposeHeaders:
        - custom-header-1
        - grpc-status
        - grpc-message
        allowCredentials: true
                                  
