# k8s-manifest.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-frontend
  labels:
    app: blog-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-frontend
  template:
    metadata:
      labels:
        app: blog-frontend
    spec:
      containers:
        - name: blog-frontend
          image: bloomingflower/blog-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: blog-frontend-secret
---
apiVersion: v1
kind: Service
metadata:
  name: blog-frontend
  labels:
    app: blog-frontend
spec:
  ports:
    - name: http-blog
      port: 80
      targetPort: 80
  selector:
    app: blog-frontend

---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: blog-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http-blog
      protocol: HTTP
    hosts:
    - "blog.yourrubber.duckdns.org"
  - port:
      number: 50031
      name: http2-blog
      protocol: HTTP2
    hosts:
    - "blog.yourrubber.duckdns.org"

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: blog-frontend-virtualservice
spec:
  hosts:
  - "blog.yourrubber.duckdns.org"
  gateways:
  - blog-gateway
  http:
  - route:
    - destination:
        host: blog-frontend.default.svc.cluster.local
        port:
          number: 80
